name: app_flutter
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  shared_preferences: ^0.5.4+3
  image_picker: ^0.6.7+22
  flutter_share: ^1.0.5
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/icons/account_circle.jpg
   - assets/icons/banner.jpg
   - assets/icons/ic_camera.png

  fonts:   
   - family: Montserrat
     fonts:
       - asset: assets/fonts/Montserrat.ttf
        

  